KEY_PRODUCT_NAME = 'PRODUCT_NAME'
KEY_RECEEVI_DOMAIN = 'RECEEVI_DOMAIN'
KEY_SUPABASE_DOMAIN = 'SUPABASE_DOMAIN'
KEY_LETSENCRYPT_EMAIL = 'LETSENCRYPT_EMAIL'
KEY_LETSENCRYPT_TOS_ACCEPTED = 'LETSENCRYPT_TOS_ACCEPTED'
KEY_SETUP_HTTPS = 'SETUP_HTTPS'
KEY_FACEBOOK_APP_SECRET = 'FACEBOOK_APP_SECRET'
KEY_WHATSAPP_ACCESS_TOKEN = 'WHATSAPP_ACCESS_TOKEN'
KEY_WHATSAPP_API_PHONE_NUMBER_ID = 'WHATSAPP_API_PHONE_NUMBER_ID'
KEY_WHATSAPP_BUSINESS_ACCOUNT_ID = 'WHATSAPP_BUSINESS_ACCOUNT_ID'
KEY_HTTP_PORT = 'HTTP_PORT'
KEY_HTTPS_PORT = 'HTTPS_PORT'

def read_file(filename: str):
    with open(filename, 'r') as file_obj:
        return file_obj.read()

def write_file(filename: str, content: str):
    with open(filename, 'w') as file_obj:
        file_obj.write(content)
